name: Test
on:
  workflow_dispatch:
  push:
    branches: ["[0-9]+.[0-9]+.x"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Build and upload
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
        env:
          CI: true